import pandas as pd
import numpy as np
from pathlib import Path

class FeatureStore:
    def __init__(self, input_path: str, output_path: str):
        self.input_path = input_path
        self.output_path = output_path

    def load_cleaned_data(self):
        return pd.read_csv(self.input_path)

    def engineer_features(self, df: pd.DataFrame):
        """
        Creates domain-specific features for EV diagnostics.
        """
        # Ensure data is sorted by time for rolling calculations
        df = df.sort_values(by='time').reset_index(drop=True)

        # 1. Power Efficiency (Mechanical Power / DC Power)
        # We add a small epsilon to avoid division by zero
        df['efficiency_ratio'] = df['Power_meca_ev'] / (df['Power_DC_ev'] + 1e-5)

        # 2. Battery Internal Resistance Proxy (Voltage Drop / Current Change)
        # Using rolling diff to see how voltage responds to current spikes
        df['delta_v'] = df['Ubat_ev'].diff().fillna(0)
        df['delta_i'] = df['I_bat_ev'].diff().fillna(0)
        df['v_i_ratio'] = (df['delta_v'] / (df['delta_i'] + 1e-5)).abs()

        # 3. Rolling Statistics (Smoothing noise out of the telemetry)
        # 5-second window (assuming 0.5s sampling rate based on your CSV)
        window = 10 
        df['rolling_soc_drop'] = df['soc_ev'].diff().rolling(window=window).mean().fillna(0)
        df['rolling_power_std'] = df['Power_DC_ev'].rolling(window=window).std().fillna(0)

        # 4. Acceleration Intensity
        # Combining mechanical power with RPM to see if the motor is overworking
        df['power_per_rpm'] = df['Power_meca_ev'] / (df['rpm'] + 1e-5)

        # 5. Cleanup: Remove any Inf or NaN values generated by calculations
        df = df.replace([np.inf, -np.inf], np.nan).fillna(0)
        
        return df

    def save_features(self, df: pd.DataFrame):
        Path(self.output_path).parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(self.output_path, index=False)
        print(f" Feature Store updated: {self.output_path}")

    def run(self):
        print(" Engineering Features...")
        df_clean = self.load_cleaned_data()
        df_features = self.engineer_features(df_clean)
        self.save_features(df_features)
        return df_features

if __name__ == "__main__":
    # Paths based on your folder structure
    PROCESSED_CSV = "data/processed/telemetry_cleaned.csv"
    FEATURES_CSV = "data/features/telemetry_features.csv"
    
    fs = FeatureStore(PROCESSED_CSV, FEATURES_CSV)
    fs.run()